name: GCM

on:
  push:
    branches: [ codespaces ]
  workflow_dispatch:

jobs:
  validate_gcm:
    name: "build-fork"

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.201

    - name: Install dependencies
      run: dotnet restore

    - name: Build Linux
      run: dotnet build --configuration LinuxRelease

    - name: Lay out
      run: |
        mkdir -p linux-build/deb linux-build/tar
        mv out/linux/Packaging.Linux/deb/Release/*.deb linux-build/deb
        mv out/linux/Packaging.Linux/tar/Release/*.tar.gz linux-build/tar

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: |
          linux-build
