name: GCM

on:
  workflow_dispatch:

jobs:
  validate_gcm:
    name: "CI"

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.201

    - name: Install dependencies
      run: dotnet restore

    - name: Build Linux
      run: dotnet build --configuration LinuxRelease
